alias cp="cp -i"
alias df='df -h'
alias free='free -m'
alias more=less
alias ls="ls --group-directories-first"
alias la="ls --group-directories-first -a"
alias please="sudo"
alias ..="cd .."
alias git.s="git status"
alias git.p="git push"
alias git.c="git commit"
alias git.m="git commit -m"
alias git.d="git diff"
alias :q="exit"
alias hh="homebank"
alias spellen="aspell -l en check"
alias spellit="aspell -l it check"
alias mutt="~/.config/neomutt/mutt-boot.sh"
